public enum PropertyType
{
    None = 0,
    ResetGravity = 1,
    KineticFriction = 2,
    Velocity = 4,
    IsKinematic = 5,
    Mass = 6,
    SoftRotationScale = 7,
    EnableTrail = 13,
    Hp = 14,
    Power = 15,
    MaxHp = 16,
    MaxPower = 17,
    Bounciness = 18,
    StaticFriction = 19,
    Gravity = 20,
    Friction = 21,
    Tyrants = 22,
    Blink_Power = 122,
    Shield = 123,
}